Dotit\SyliusHighlightingPlugin\Entity\ProductHighlighting:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [name]
        message: 'dotit_sylius_highlighting_plugin.product_highlighting.name.unique'
        groups: ['dotit_product']
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [slug]
        message: 'dotit_sylius_highlighting_plugin.product_highlighting.slug.unique'
        groups: ['dotit_product']

  properties:
    name:
      - NotBlank:
          message: 'dotit_sylius_highlighting_plugin.product_highlighting.name.not_blank'
          groups: ['dotit_product']
      - Length:
          min: 2
          max: 250
          minMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.name.min_length'
          maxMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.name.max_length'
          groups: ['dotit_product']
    description:
      - NotBlank:
          message: 'dotit_sylius_highlighting_plugin.product_highlighting.description.not_blank'
          groups: [ 'dotit_product' ]
      - Length:
          min: 2
          max: 250
          minMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.description.min_length'
          maxMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.description.max_length'
          groups: [ 'dotit_product' ]

    slug:
      - NotBlank:
          message: 'dotit_sylius_highlighting_plugin.product_highlighting.slug.not_blank'
          groups: ['dotit_product']
      - Length:
          min: 2
          max: 250
          minMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.slug.min_length'
          maxMessage: 'dotit_sylius_highlighting_plugin.product_highlighting.slug.max_length'
          groups: ['dotit_product']



